# Generated by Django 5.2.8 on 2025-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('servico', models.CharField(max_length=100, verbose_name='Serviço Solicitado')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início da Folga')),
                ('data_fim', models.DateTimeField(verbose_name='Fim da Folga')),
                ('motivo', models.CharField(blank=True, max_length=100, verbose_name='Motivo (Opcional)')),
            ],
            options={
                'verbose_name': 'Folga / Bloqueio',
                'verbose_name_plural': 'Folgas / Bloqueios',
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Horário Disponível')),
                ('reservado', models.BooleanField(default=False, verbose_name='Já Reservado?')),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
            ],
            options={
                'verbose_name': 'Serviço',
            },
        ),
    ]
